-- Fix symbology mappings to match Android app EBarcodesSymbologies integer values
USE barcode_wms;

-- Clear existing symbology mappings
DELETE FROM symbology_types;

-- Insert correct mappings based on Android app fromInt() method
INSERT INTO symbology_types (id, name, description) VALUES
(-1, 'UNKNOWN', 'Unknown symbology type'),
(1, 'CODABAR', 'Codabar barcode'),
(2, 'CODE11', 'Code 11 barcode'),
(3, 'CODE39', 'Code 39 barcode'),
(4, 'AZTEC', 'Aztec 2D barcode'),
(5, 'CODE93', 'Code 93 barcode'),
(6, 'CODE128', 'Code 128 barcode'),
(7, 'COMPOSITE_AB', 'Composite AB barcode'),
(8, 'COMPOSITE_C', 'Composite C barcode'),
(9, 'D2OF5', 'Discrete 2 of 5 barcode'),
(10, 'DATAMATRIX', 'Data Matrix 2D barcode'),
(11, 'DOTCODE', 'DotCode 2D barcode'),
(12, 'EAN_8', 'EAN-8 barcode'),
(13, 'EAN_13', 'EAN-13 barcode'),
(14, 'GRID_MATRIX', 'Grid Matrix 2D barcode'),
(15, 'GS1_DATABAR', 'GS1 DataBar barcode'),
(16, 'GS1_DATABAR_EXPANDED', 'GS1 DataBar Expanded barcode'),
(17, 'GS1_DATABAR_LIM', 'GS1 DataBar Limited barcode'),
(18, 'GS1_DATAMATRIX', 'GS1 Data Matrix barcode'),
(19, 'GS1_QRCODE', 'GS1 QR Code barcode'),
(20, 'HANXIN', 'Han Xin Code 2D barcode'),
(21, 'I2OF5', 'Interleaved 2 of 5 barcode'),
(22, 'MAXICODE', 'MaxiCode 2D barcode'),
(23, 'MICROPDF', 'MicroPDF417 barcode'),
(24, 'MICROQR', 'Micro QR Code barcode'),
(25, 'MSI', 'MSI barcode'),
(26, 'AUSTRALIAN_POSTAL', 'Australian Postal barcode'),
(27, 'CANADIAN_POSTAL', 'Canadian Postal barcode'),
(28, 'CHINESE_2OF5', 'Chinese 2 of 5 barcode'),
(29, 'DUTCH_POSTAL', 'Dutch Postal barcode'),
(30, 'FINNISH_POSTAL_4S', 'Finnish Postal 4-State barcode'),
(31, 'JAPANESE_POSTAL', 'Japanese Postal barcode'),
(32, 'KOREAN_3OF5', 'Korean 3 of 5 barcode'),
(33, 'MAILMARK', 'Royal Mail Mailmark barcode'),
(34, 'MATRIX_2OF5', 'Matrix 2 of 5 barcode'),
(35, 'PDF417', 'PDF417 2D barcode'),
(36, 'QRCODE', 'QR Code 2D barcode'),
(37, 'TLC39', 'TLC-39 barcode'),
(38, 'TRIOPTIC39', 'Trioptic Code 39 barcode'),
(39, 'UK_POSTAL', 'UK Postal barcode'),
(40, 'UPC_A', 'UPC-A barcode'),
(41, 'UPC_E', 'UPC-E barcode'),
(42, 'UPCE1', 'UPC-E1 barcode'),
(43, 'USPLANET', 'USPS PLANET barcode'),
(44, 'USPOSTNET', 'USPS POSTNET barcode'),
(45, 'US4STATE', 'USPS 4-State barcode'),
(46, 'US4STATE_FICS', 'USPS 4-State FICS barcode');